---
title: "Physiology & Behaviour Analysis"
author: "Maureen Anne Williams"
date: "`r Sys.Date()`"
output:   
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load packages and prep data
```{r}
library("mgcv")
library("lme4")
library("plyr")
library("ggplot2")
library("cowplot")
total<-read.csv("total_budget_2.csv", header=T, stringsAsFactors = F) #load total physiology spreadsheet, top row headers, strings are not factors

attach(total) #attach physiology sheet
total[total == "#N/A"] <- NA #Make sure NAs read as NAs
str(total) #check structure of the dataset

#Structure the total physiology dataset for analysis
total$resp_rate<-as.numeric(total$resp_rate)
total$dryweight_mg<-as.numeric(total$dryweight_mg) 
total$gam_dryweight_mg<-as.numeric(total$gam_dryweight_mg) 
total$inf_status<-as.factor(total$inf_status)
total$sex<-as.factor(total$sex)
total$gammarus<-as.factor(total$gammarus)
total$temp<-as.numeric(total$temp)
total$blanks<-as.numeric(total$blanks)
total$saturation<-as.numeric(total$saturation)
total$volume_liter<-as.numeric(total$volume_liter)
total$change_percent<-as.numeric(total$change_percent)
total$time_h<-as.numeric(total$time_h)
total$assimilation<-as.numeric(total$assimilation)
total$filter_dw_initial<-as.numeric(total$filter_dw_initial)
total$filter_dw_final<-as.numeric(total$filter_dw_final)
total$poop_weight<-as.numeric(total$poop_weight)
total$efficiency<-as.numeric(total$efficiency)
total$init_wet_gam<-as.numeric(total$init_wet_gam)
total$leaf_change<-as.numeric(total$leaf_change)
total$rate<-as.numeric(total$rate)
total$feeding_rate<-as.numeric(total$feeding_rate)
total$resp_rate_uncorrected<-total$resp_rate*total$dryweight_mg
str(total)
total$quad<-total$temp^2
#Load the behaviour dataset 
behav_total<-read.csv("behaviour_total.csv", header=T, stringsAsFactors = F)
#Structure the total behaviour dataset for analysis
behav_total$geo_score<-as.numeric(behav_total$geo_score)
behav_total$photo_score<-as.numeric(behav_total$photo_score)
behav_total$photo_score10<-as.numeric(behav_total$photo_score)*10
behav_total$inf_status<-as.factor(behav_total$inf_status)
behav_total$temp<-as.numeric(behav_total$temp)
behav_total$gam_id<-as.factor(behav_total$gam_id)
behav_total$sex<-as.factor(behav_total$sex)

##Load modified physiology datasets for easy plotting
feeding<-read.csv("feeding_Joules.csv", header=T, stringsAsFactors = F)
growth_all<-read.csv("gamm_sizechange_1.csv", header=T, stringsAsFactors = F)
resp_clean<-read.csv("resp_joules_clean.csv", header=T, stringsAsFactors = F)
eff<-read.csv("efficiency.csv", header=T, stringsAsFactors = F)
ass<-read.csv("ass.csv", header=T, stringsAsFactors = F)

```

#Physiology Analysis
##Feeding anaylsis 
```{r}
#Generate feeding models
feeding_GAM<-gam(total$feeding_rate~total$inf_status+s(total$temp,k=4)+s(total$temp,k=4,by=total$inf_status))
feeding_GLM<-glm(total$feeding_rate~total$inf_status*total$temp*total$quad)
#generate feeding AICs
AIC(feeding_GAM)
AIC(feeding_GLM)
#generate feeding model tables 
anova(feeding_GAM)
summary(feeding_GLM)
```

##Respiration analysis
```{r}
#Generate respiration models
resp_GAM<-gam(total$resp_rate~total$inf_status+s(total$temp,k=6)+s(total$temp,k=6,by=total$inf_status), method="REML")
resp_GAM_nosex<-gam(total$resp_rate~total$inf_status+s(total$temp,k=6)+s(total$temp,k=6,by=total$inf_status), method="REML")
cresp_GAM<-gam(total$resp_rate~s(total$temp,k=4)+total$sex, method="REML")
resp_GLM<-glm(total$resp_rate~total$inf_status*total$temp*total$quad)
##generate respiration AICs
AIC(resp_GAM)
AIC(resp_GLM)
##generate respiration model tables 
anova(resp_GAM)
summary(resp_GLM)
```

##Growth analysis
```{r}
#Generate growth models
growth_GAM<-gam(total$rate~total$inf_status+s(total$temp,k=4)+s(total$temp,k=4,by=total$inf_status))
growth_GLM<-glm(total$rate~total$inf_status*total$temp*total$quad)
##generate growth AICs
AIC(growth_GAM)
AIC(growth_GLM)
##generate growth model tables 
anova(growth_GAM)
summary(growth_GLM)
```

##Efficiency analysis
```{r}
#Generate efficiency models
eff_GAM<-gam(total$efficiency~total$inf_status+s(total$temp,k=4)+s(total$temp,k=4,by=total$inf_status))
eff_GLM<-glm(total$efficiency~total$inf_status*total$temp*total$quad)
##generate eff AICs
AIC(eff_GAM)
AIC(eff_GLM)
##generate eff model tables 
anova(eff_GAM)
summary(eff_GLM)
```

##Assimilation analysis
```{r}
#Generate assimilation models
ass_GAM<-gam(total$assimilation~total$inf_status+s(total$temp,k=4)+s(total$temp,k=4,by=total$inf_status))
ass_GLM<-glm(total$assimilation~total$inf_status*total$temp*total$quad)
##generate assimilation AICs
AIC(ass_GAM)
AIC(ass_GLM)
##generate assimilation model tables 
anova(ass_GAM)
summary(ass_GLM)

```



#Behaviour Analysis
##Initial Weights T.Test
```{r}
beh_weight<-read.csv("weights_1.csv")
beh_inf <- beh_weight$init_wetweight[beh_weight$inf_status == "I"]
beh_uninf <- beh_weight$init_wetweight[beh_weight$inf_status == "U"]
t.test(beh_inf,beh_uninf)
t.test(beh_inf,beh_uninf,var.equal=TRUE)
t.test(beh_uninf,beh_inf)
```

##Full Behaviour Analysis, All Runs
```{r}
options(na.action='na.exclude')

str(behav_total$temp)
b2 <- gamm(photo_score~s(temp,k=4)+inf_status, family=poisson,
           data=behav_total,random=list(gam_id=~1))
plot(b2$gam,pages=1)
anova(b2$gam) 

#Phototaxis
LMER_full_photo <-
  lmer(photo_score ~ inf_status + temp+ (1 |gam_id),
       REML = FALSE,
       data = behav_total)

LMER_interacting_photo<-
  lmer(photo_score ~ inf_status * temp+ (1 |gam_id),
       REML = FALSE,
       data = behav_total)
LMER_interacting_photo_quad<-
  lmer(photo_score ~ inf_status * temp+ temp^2+ (1 |gam_id),
       REML = FALSE,
       data = behav_total)

LMER_notemp_photo <-
  lmer(photo_score ~ inf_status + (1 |gam_id),
       REML = FALSE,
       data = behav_total)

LMER_noinf_photo <-
  lmer(photo_score ~ temp + (1 |gam_id),
       REML = FALSE,
       data = behav_total)

anova(LMER_full_photo, LMER_noinf_photo)
anova(LMER_full_photo, LMER_interacting_photo)
anova(LMER_full_photo, LMER_notemp_photo)

#Geotaxis
LMER_full_geo <-
  lmer(geo_score ~ inf_status + temp+ (1 |gam_id),
       REML = FALSE,
       data = behav_total)

par(mfrow=c(2,2)) # init 4 charts in 1 panel
qqnorm(residuals(LMER_full_geo))
leveneTest(residuals(LMER_full_geo) ~ behav_total$temp)

LMER_interacting_geo_quad<-
  lmer(geo_score ~ inf_status * temp+ temp^2+ (1 |gam_id),
       REML = FALSE,
       data = behav_total)

LMER_notemp_geo <-
  lmer(geo_score ~ inf_status + (1 |gam_id),
       REML = FALSE,
       data = behav_total)


LMER_noinf_geo <-
  lmer(geo_score ~ temp + (1 |gam_id),
       REML = FALSE,
       data = behav_total)

anova(LMER_full_geo, LMER_noinf_geo)
anova(LMER_full_geo, LMER_interacting_geo)
anova(LMER_full_geo, LMER_notemp_geo)

behav_total$temp<-as.factor(behav_total$temp)
library(multcomp)
geo_diff<-lsmeans(LMER_full_geo, pairwise~temp*inf_status, adjust="tukey")
photo_diff<-lsmeans(LMER_full_photo, pairwise~temp*inf_status, adjust="tukey")

```

#Data summaries
```{r}
feeding_summary <- ddply(feeding, c("inf_status", "temp"), summarise,
                         N    = length(aver),
                         mean = mean(aver),
                         sd   = sd(aver),
                         se   = sd / sqrt(N)
)
growth_all$weight_change<-growth_all$weight_change/(1000000000)
growth_summary <- ddply(growth_all, c("inf_status", "temp"), summarise,
                        N    = length(weight_change),
                        mean = mean(weight_change),
                        sd   = sd(weight_change),
                        se   = sd / sqrt(N)
)

resp_summary <- ddply(resp_clean, c("inf_status", "temp"), summarise,
                      N    = length(resprate),
                      mean = mean(resprate),
                      sd   = sd(resprate),
                      se   = sd / sqrt(N)
)
resp_summary$survival<-resp_summary$N/15
ass_summary <- ddply(ass, c("inf_status", "temp"), summarise,
                     N    = length(ass),
                     mean = mean(ass),
                     sd   = sd(ass),
                     se   = sd / sqrt(N)
)

eff_summary <- ddply(eff, c("inf_status", "temp"), summarise,
                     N    = length(efficiency),
                     mean = mean(efficiency),
                     sd   = sd(efficiency),
                     se   = sd / sqrt(N)
)

geo_summary <- ddply(behav_total, c("inf_status", "temp"), summarise,
                     N    = length(geo_score),
                     mean = mean(geo_score,na.rm=T),
                     median= median(geo_score, na.rm=T),
                     sd   = sd(geo_score,na.rm=T),
                     se   = sd / sqrt(N)
)

photo_summary <- ddply(behav_total, c("inf_status", "temp"), summarise,
                       N    = length(photo_score),
                       mean = mean(photo_score, na.rm=T),
                       median= median(photo_score, na.rm=T),
                       sd   = sd(photo_score, na.rm=T),
                       se   = sd / sqrt(N)
)

photo_summary_print <- ddply(behav_total, c("inf_status"), summarise,
                             N    = length(photo_score),
                             mean = mean(photo_score),
                             sd   = sd(photo_score),
                             se   = sd / sqrt(N)
)

```

#Plotting

##Physiology
```{r}

respplot<-ggplot(resp_summary, aes(x=temp, y=mean, fill=inf_status, group=inf_status, color=inf_status)) + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.3, position=pd, color="#000000") +
  geom_point(size=2, position=pd, shape= 21, colour="black")+
  scale_fill_manual(values=c("black", "white"))+
  #scale_colour_manual(values=c("gray", "black"))+
geom_smooth(aes(group = 1), method='glm', se=FALSE, colour="black")+
stat_smooth(aes(group = 1), method = "glm", colour = "black", geom = "ribbon",linetype=2, fill = NA)+
    xlab("")+
  ylab("Respiration\n (J/mg/h)")+
  scale_x_continuous(breaks = c(3, 6, 9, 12, 15, 18))+
  theme(panel.grid.major = element_blank(), legend.key=element_rect(fill='white'),
        legend.position = c(0.3, 0.8), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.text=element_text(size=12),
        axis.title=element_text(size=12),
        axis.line = element_line(colour = "black"))

effplot<-ggplot(eff_summary, aes(x=temp, y=mean)) + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se, fill=inf_status, group=inf_status), width=.3, position=pd, color="#000000") +
  geom_point(aes(fill=inf_status, group=inf_status), size=2, position=pd, shape= 21, colour="black")+
  scale_fill_manual(values=c("black", "white"))+
  xlab("Temperature °C")+
  ylab("Efficiency (%)")+
    scale_x_continuous(breaks = c(3, 6, 9, 12, 15, 18))+
  theme(panel.grid.major = element_blank(), 
        legend.position = "none", panel.grid.minor = element_blank(),
        axis.text=element_text(size=12),
        axis.title=element_text(size=12),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))

feedingplot2<-ggplot(feeding_summary, aes(x=temp, y=mean, fill=inf_status, group=inf_status)) + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.3, position=pd, color="#000000") +
  geom_point(size=2, position=pd, shape= 21, colour="black")+
  scale_fill_manual(values=c("black", "white"))+
  geom_smooth(aes(group = 1), method='glm', se=FALSE, colour="black")+
stat_smooth(aes(group = 1), method = "glm", colour = "black", geom = "ribbon",linetype=2, fill = NA)+
  xlab("")+
  ylab("Consumption\n(mg/day/mg)")+
    scale_x_continuous(breaks = c(3, 6, 9, 12, 15, 18))+
  scale_shape_manual(values=c(1,19))+
  theme(panel.grid.major = element_blank(), legend.position = "none", 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        axis.text=element_text(size=12),
        axis.title=element_text(size=12))

growthplot<-ggplot(growth_summary, aes(x=temp, y=mean, fill=inf_status, group=inf_status)) + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.3, position=pd, color="#000000") +
  geom_point(size=2, position=pd, shape= 21, colour="black")+
  scale_fill_manual(values=c("black", "white"))+
  xlab("")+
  ylab("Growth rate\n(mg/day)")+
      scale_x_continuous(breaks = c(3, 6, 9, 12, 15, 18))+
  theme(panel.grid.major = element_blank(), legend.position = "none", 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        axis.text=element_text(size=12),
        axis.title=element_text(size=12))

assplot<-ggplot(ass_summary, aes(x=temp, y=mean, fill=inf_status, group=inf_status)) + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.3, position=pd, color="#000000") +
  geom_point(size=2, position=pd, shape= 21, colour="black")+
  scale_fill_manual(values=c("black", "white"))+
    scale_x_continuous(breaks = c(3, 6, 9, 12, 15, 18))+
  xlab("")+
  ylab("Assimilation\n(J/day)")+
  theme(panel.grid.major = element_blank(), 
        legend.position = "none", panel.grid.minor = element_blank(),
        axis.text=element_text(size=12),
        axis.title=element_text(size=12),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))


pcol<-plot_grid(NULL,
                 respplot + theme(legend.position="none"),
                NULL,
                 feedingplot2 + theme(legend.position="none"),
                NULL, 
                assplot + theme(legend.position="none"),
                NULL, 
                growthplot + theme(legend.position="none"),
                NULL, 
                effplot + theme(legend.position="none"),
                 align = 'vh',
                 labels=c("(a)","","(b)","","(c)","","(d)","","(e)"),
                 hjust = -1,
                 nrow = 5,
                rel_widths = c(0.12, 0.75,0.05, 0.05, 0.05,0.05,0.05,0.05,0.05,0.05)
)
plot_grid(NULL,pcol, ncol = 1, nrow=2, rel_heights = c(0.05,1.0))
```



##Behaviour
```{r}
photo_summary$xloc<- photo_summary$temp+0.5
photo_summary$yloc<- NA
photo_summary$yloc<- as.numeric(photo_summary$yloc)
photo_summary$yloc <- photo_summary$mean-5
photo_summary$yloc[photo_summary$inf_status == "U" & photo_summary$temp== "3"] <- 34

    photo_summary$temp<-as.numeric(photo_summary$temp)


photoplot<-ggplot(photo_summary, aes(x=temp, y=mean, fill=inf_status), group=inf_status) + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.3, position=pd, color="#000000") +
  geom_point(size=2, position=pd, shape= 21, colour="black")+
  scale_fill_manual(values=c("black", "white"))+
  xlab("")+
  ylab("Phototaxis Score")+
  xlim(2.5,19)+
  geom_smooth(aes(linetype=inf_status), method='glm', se=FALSE, colour="black")+
  stat_smooth(aes(linetype=inf_status), method = "glm", colour = "black", geom = "ribbon", fill = NA)+
      scale_x_continuous(breaks = c(3, 6, 9, 12, 15, 18))+
  scale_shape_manual(values=c(1,19))+
  theme(panel.grid.major = element_blank(),  
        axis.text=element_text(size=12,color = "black"),
        axis.title=element_text(size=12),
        legend.position="none", panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))


    geo_summary$temp<-as.numeric(geo_summary$temp)

geo_summary$xloc<- geo_summary$temp+0.5
geo_summary$yloc<- NA
geo_summary$yloc[geo_summary$inf_status == "U" & geo_summary$temp== "3"] <- 10

geoplot<-ggplot(geo_summary, aes(x=temp, y=mean)) + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se, fill=inf_status, group=inf_status), width=.3, position=pd, color="#000000") +
  geom_point(aes(fill=inf_status, group=inf_status), size=2, position=pd, shape= 21, colour="black")+
  scale_fill_manual(values=c("black", "white"))+
  xlab("Temperature °C")+
  ylab("Geotaxis Score")+
  xlim(2.5,19)+ 
  geom_smooth(aes(linetype=inf_status),method='glm', se=FALSE, colour="black")+
  stat_smooth(aes(linetype=inf_status),method = "glm", colour = "black", geom = "ribbon", fill = NA)+
  scale_x_continuous(breaks = c(3, 6, 9, 12, 15, 18))+
  #geom_smooth(method='lm', se=F, formula = y~x)+
  #geom_smooth(method='glm', se=FALSE, colour="black")+
 # stat_smooth(method = "glm", colour = "black", geom = "ribbon",linetype=2, fill = NA)+
  scale_shape_manual(values=c(1,19))+
  theme(panel.grid.major = element_blank(),
        axis.text=element_text(size=12, color = "black"),
        axis.title=element_text(size=12),
        legend.position="none", panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))



plot_grid(photoplot,geoplot,
          labels=c("(a)","(b)"),
          ncol=1, nrow=2)
```

